---
- name: Create /home/_work/ directory on target servers
  hosts: all
  become: yes
  tasks:
    - name: Ensure /home/_work2/ directory exists
      file:
        path: /home/_work2/
        state: directory
        mode: '0755'
